replicaCount: 3

image:
  repository: gambtho/vstslinux
  tag: 1.0
  pullPolicy: Always

service:
  type: ClusterIP

vsts:
  account: ""
  token: ""
  pool: ""

ingress:
  enabled: true
  annotations: {}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: vstslinuxbuild
          servicePort: https
  tls:
    - secretName: tls-secret
      hosts:
        - chart-example.local

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  - name: VSTS_ACCOUNT
    valueFrom:
      secretKeyRef:
        name: vsts
        key: account
  - name: VSTS_TOKEN
    valueFrom:
      secretKeyRef:
        name: vsts
        key: token
  - name: VSTS_POOL
    valueFrom:
      secretKeyRef:
        name: vsts
        key: pool   
